### ISSUE TITLE
Monster Healing/Temp hit points

### ISSUE THREAD

**Issue by Karieo** [mouse0270/Beyonds-Toolbox#7]
The encounters allow you to heal over the base amount after setting the monster initial health.  This can be good for monster that can gain temporary hit points, but if you use the scroll wheel feature, the hit points will jump down to the initial base hit points. e.g. if I add a monster with 10 hp and it somehow receives 10 temp hp, thus now having 20 hp.  Then I mouse over and use the scroll wheel to scroll up or down the hp drops to 10 hp on the first scroll notch.  Let me know if you have any more questions.

**Comment by mouse0270** [comment]
Wow thanks for pointing this out I made it so you. Could heal higher then max just for temp healing points but I never really tested taking damage after adding the ability to go over. This is an easy fix I can patch today.

**Comment by Karieo** [comment]
Sure thing. Let me know where else I can help.

**Comment by mouse0270** [comment]
This has been pushed into the current master branch and will be included in the next update.

Please be advised that you cant add temp health with the mouse wheel you have to click on the health and heal past the max. It just prevents the health from being reset to max if you have over max and mouse wheel down.
